<?php

/** @var \TrainingUnit3\BlockExercises\Block\HelloWorldBlock $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<h1>Hello World - I am from block</h1>
<form action="template/create" method="post">
<!--    <input name="form_key" type="hidden" value="--><?php //echo $block->getFormKey();?><!--">-->
    <input type="text" name="firstname" value="">
    <input type="submit" name="Submit">
</form>
